#!/usr/bin/env python

import numpy as np

from pycrazyswarm import *
import uav_trajectory

if __name__ == "__main__":
    swarm = Crazyswarm()
    timeHelper = swarm.timeHelper
    allcfs = swarm.allcfs

    traj1 = uav_trajectory.Trajectory()
    traj2 = uav_trajectory.Trajectory()
    traj3 = uav_trajectory.Trajectory()
    traj4 = uav_trajectory.Trajectory()
    traj5 = uav_trajectory.Trajectory()
    traj6 = uav_trajectory.Trajectory()
    traj7 = uav_trajectory.Trajectory()
    traj8 = uav_trajectory.Trajectory()
    traj9 = uav_trajectory.Trajectory()
    
    # upload csv
    traj1.loadcsv(".csv")
    traj2.loadcsv(".csv")
    traj3.loadcsv(".csv")
    traj4.loadcsv(".csv")
    traj6.loadcsv(".csv")
    traj7.loadcsv(".csv")
    traj8.loadcsv(".csv")
    traj9.loadcsv(".csv")
    ids=[1,2,3,4,6,7,8,9]

    TRIALS = 1
    TIMESCALE = 1.0
    for i in range(TRIALS):
        for cf in allcfs.crazyflies:
            cf.uploadTrajectory(1, 0, traj1)
            cf.uploadTrajectory(2, 0, traj2)
            cf.uploadTrajectory(3, 0, traj3)
            cf.uploadTrajectory(4, 0, traj4)
            cf.uploadTrajectory(5, 0, traj5)
            cf.uploadTrajectory(6, 0, traj6)
            cf.uploadTrajectory(7, 0, traj7)
            cf.uploadTrajectory(8, 0, traj8)
            cf.uploadTrajectory(9, 0, traj9)
        
        # take off
        allcfs.takeoff(targetHeight=1.0, duration=1.0)
        timeHelper.sleep(2.0)
        
        # cfs in a row
        for cf in allcfs.crazyflies:
            pos = np.array(cf.initialPosition) + np.array([0, 0, 1.0])
            cf2.goTo(pos - 0.5, pos, 1.0)
            cf8.goTo(pos + 0.5, pos, 1.0)
            timeHelper.sleep(1.5)
            cf1.goTo(pos - 1.0, pos - 1.0, 1.0)
            cf3.goTo(pos, pos + 1.0, 1.0)
            cf4.goTo(pos - 0.5, pos - 1.0, 1.0)
            cf6.goTo(pos + 0.5, pos + 1.0, 1.0)
            cf7.goTo(pos, pos - 1.0, 1.0)
            cf9.goTo(pos + 1.0, pos + 1.0, 1.0)
            
        timeHelper.sleep(2.5)
        
        # excute traj
        for cf in allcfs.crazyflies:
            cf.startTrajectory(cf.id-1)
        timeHelper.sleep(traj1.duration * TIMESCALE + 2.0)

        # land
        allcfs.land(targetHeight=0.06, duration=2.0)
        timeHelper.sleep(3.0)
